name: Continuous Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Update to v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2 # Update to v2
        with:
          distribution: 'temurin' # 'temurin' distribution provides OpenJ9 builds of the OpenJDK
          java-version: '11'

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v2 # Update to v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Unit and Integration Tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: mvn clean verify
